name: flutter_application_1
description: A new Flutter project.

environment:
  sdk: '>=3.0.0 <4.0.0'

flutter:
  uses-material-design: true
  assets:
    - assets/images/automag_logo.png  

dev_dependencies:
  flutter_lints: ^3.0.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.5 
  